name: Ubports Alioth
run-name: Ubports Alioth

on:
  push:
    branches: [ rebase ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Ubports Alioth
        run: |
         sudo apt install -y pip git mono-devel build-essential lld uuid-dev iasl nasm gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf python2 gettext locales gnupg ca-certificates python3-venv git git-core clang llvm curl mkbootimg
         bash build.sh
        env:
           token: ${{ secrets.TOKEN }}
           chat_id: ${{ secrets.CHAT_ID }}
